name: Prueba

on: 
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest
    name: A job to run test
    steps:
    - name: Clone repository manually
      run: git clone https://github.com/MasterCloudApps/Template-CI-CD .
    - name: Checkout action
      uses: actions/checkout@v2
      with:
        path: ./action
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
    - name: Run Maven Action
      id: maven-gha
      uses: ./action/
      with:
        package: false
        exclude: 'selenium'
    - name: Get project version
      run: |
        [[ ${{ steps.maven-gha.outputs.project-version }} == "0.1.0" ]] && echo "Works" || ( echo "Fail" && exit 1 )
